In [2]:
import tmdbsimple as tmdb
tmdb.API_KEY = 'b8ab01d0873c83efc0847a932b724068'

In [3]:
#Example Queries for TMDb API
movie = tmdb.Movies(603)
response = movie.info()
movie.top_rated()

In [192]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob
import os
from datetime import datetime
from operator import mul

pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.max_columns', None)

In [275]:
# Looping through data folder to concat CSV's into one big dataframe
# 13708 rows in dataset
# 12856 with Dom Gross
# Reinitialize HERE

for i,name in enumerate(glob.glob('data/*')):
    if i == 0:
        df = pd.read_csv(name)
    df2 = pd.read_csv(name)
    concat = pd.concat([df,df2],ignore_index=True)
    df = concat

#Drop Empty Dom Gross rows
df=df.dropna(subset=['Domestic   Gross'])
df=df.drop(['Desc'],axis=1)
df=df.drop(['Prod Co'],axis=1)

#Rename Columns
df.rename(columns={'Run-  time':'Runtime','Domestic   Gross':'Dom_Gross', 
                   'International   Gross':'Intl_Gross', 'Worldwide   Gross':'WW_Gross',
       'Dom   Locs':'Dom_Locs'}, inplace=True)

In [276]:
df.columns

Index(['Mcode', 'Dist', 'Picture', 'Format', 'Rtg', 'Rel Date', 'Dom_Gross',
       'Intl_Gross', 'WW_Gross', 'Dom_Locs', 'Opng Wknd   Gross',
       'Wknd   Days', 'Wknd   Multi', 'Wk   Multi', 'Runtime', 'Genre', 'TM',
       'CS', 'Pattern'],
      dtype='object')

In [258]:
df

          Mcode Dist                          Picture Format   Rtg   Rel Date  Domestic   Gross  International   Gross  Worldwide   Gross  Dom   Locs  Opng Wknd   Gross  Wknd   Days  Wknd   Multi  Wk   Multi Run-  time             Genre    TM   CS    Pattern  Year  Month  Week Num
0      20064870  RKO  Snow White And The Seven Dwarfs     2D     G 2037-12-21       118328683.0             40696013.0        159024696.0         NaN                NaN            3           NaN         NaN       1:23   Anim, Child/Fam   NaN  NaN       Wide  2037     12        52
1      20064877   UA                Wuthering Heights     2D    NR 2039-04-13          624643.0                    NaN           624643.0         NaN                NaN            3           NaN         NaN       1:43             Drama   NaN  NaN  Exclusive  2039      4        15
2      20064878  MGM                Wizard Of Oz, The     2D     G 2039-08-25        24297264.0               158197.0         24455461.0         NaN                NaN            3           NaN         NaN       1:41  Child/Fam, Music   NaN  NaN       Wide  2039      8        34
3      20064688  MGM               Gone With The Wind     2D     G 2039-12-15        10903237.0            191900000.0        202803237.0         NaN                NaN            3           NaN         NaN       3:42     Drama, Period   NaN  NaN  Exclusive  2039     12        50
4      20064850  RKO                 Pinocchio (1940)     2D     G 2040-02-23        45277597.0               912988.0         46190585.0         NaN                NaN            3           NaN         NaN       1:27   Anim, Child/Fam   NaN  NaN  Exclusive  2040      2         8
...         ...  ...                              ...    ...   ...        ...               ...                    ...                ...         ...                ...          ...           ...         ...        ...               ...   ...  ...        ...   ...    ...       ...
13703  20065650   WB                       Just Mercy     2D  PG13 2019-12-25        36046000.0             14810319.0         50856319.0         4.0           107858.0            3           NaN         NaN       2:17    Drama, Urb/Eth  83.0   A+  Exclusive  2019     12        52
13704  20071157  SON               Little Women - SON     2D    PG 2019-12-25       108101215.0            101000000.0        209101215.0      3308.0         16755310.0            3           6.5         3.2       2:15     Drama, Period  95.0   A-       Wide  2019     12        52
13705  20073195  SCL                    Song Of Names     2D  PG13 2019-12-25         1077584.0                30852.0          1108436.0        10.0            39452.0            3           NaN         NaN       1:53             Drama  42.0  NaN    Limited  2019     12        52
13706  20069660  20C          Spies In Disguise (Ani)     3D    PG 2019-12-25        66757013.0            104859751.0        171616764.0      3502.0         13354798.0            3           5.0         2.4       1:42   Anim, Child/Fam  73.0   A-       Wide  2019     12        52
13707  20072176  NEO                         Clemency     2D     R 2019-12-27          364716.0                    NaN           364716.0         2.0            35444.0            3           NaN         NaN       1:52             Drama  92.0  NaN  Exclusive  2019     12        52

[12856 rows x 22 columns]

In [277]:
#Set Rel Date to Date Time obj
df['Rel Date'] = pd.to_datetime(df['Rel Date'])
#Fixing Year Century error around 1970 (was applying to 2070)
#df['Rel Date'] = df['Rel Date'].apply(lambda x: x.replace(year = x.year - 100))

#Separating Rel Date into Year and Month
df['Year'] = df['Rel Date'].dt.year
df['Month'] = df['Rel Date'].dt.month
df['Week Num'] = df['Rel Date'].dt.week

#Applying 2D to NaN Format
df['Format'] = df['Format'].apply(lambda x: "2D" if pd.isnull(x) else x)

# Remove $ and convert to float
df[df.columns[6:9]] = df[df.columns[6:9]].replace('[\$,]', '', regex=True).astype(float)
df[df.columns[10]] = df[df.columns[10]].replace('[\$,]', '', regex=True).astype(float)

In [279]:
df.Runtime.unique()

array(['1:23', '1:43', '1:41', '3:42', '1:27', '1:59', nan, '1:09',
       '1:42', '1:34', '1:16', '2:18', '2:05', '1:53', '1:17', '1:45',
       '1:52', '3:01', '1:55', '1:15', '1:30', '1:51', '3:39', '2:55',
       '3:21', '1:50', '2:07', '2:16', '1:49', '3:02', '1:20', '2:33',
       '3:00', '2:06', '2:12', '3:40', '2:20', '2:11', '1:33', '2:28',
       '2:50', '1:56', '2:54', '2:10', '3:17', '2:47', '1:47', '1:40',
       '1:18', '2:29', '2:31', '1:54', '2:15', '2:34', '3:04', '1:37',
       '2:02', '1:28', '2:00', '2:17', '2:04', '1:57', '2:01', '1:38',
       '1:46', '2:09', '1:35', '1:44', '1:31', '3:20', '2:45', '1:29',
       '2:03', '2:08', '2:13', '1:26', '1:36', '1:58', '4:03', '3:03',
       '2:23', '1:39', '1:48', '2:14', '2:26', '1:25', '1:32', '2:36',
       '2:30', '1:22', '1:24', '3:08', '2:37', '1:19', '3:13', '3:47',
       '2:38', '2:21', '2:43', '2:40', '2:24', '2:22', '2:25', '1:14',
       '2:35', '1:21', '2:32', '2:51', '2:44', '2:41', '4:27', '6:00',
       '1:12', '1:10', '1:13', '3:18', '1:11', '4:00', '3:07', '3:09',
       '2:39', '4:14', '2:19', '3:05', '3:11', '3:48', '2:49', '0:55',
       '1:00', '0:42', '2:57', '1:01', '0:51', '4:39', '3:10', '2:42',
       '4:02', '0:58', '3:30', '0:38', '0:53', '2:27', '3:14', '0:44',
       '4:30', '2:48', '0:52', '0:56', '2:52', '0:45', '0:40', '0:39',
       '1:04', '1:05', '0:46', '2:53', '3:37', '0:48', '3:43', '3:23',
       '4:06', '2:58', '0:32', '0:57', '3:49', '6:38', '0:49', '1:03',
       '2:56', '0:47', '6:03', '1:06', '2:59', '3:12', '2:46', '4:17',
       '0:43', '9:10', '4:10', '1:08', '0:18', '3:54', '0:35'],
      dtype=object)

In [291]:
df['Runtime'].transform(lambda x: runtime_calc(x))

0        None
1        None
2        None
3        None
4        None
         ...
13703    None
13704    None
13705    None
13706    None
13707    None
Name: Runtime, Length: 12856, dtype: object

In [284]:
type()

str

In [286]:
def runtime_calc(x):
    if type(x) == 'str':
        runtime = x.split(':')
        runtime_int = [int(x1) for x1 in runtime]
        return runtime_int[0]*60 + runtime_int[1]

In [290]:
runtime = df['Runtime'].iloc[-1].split(':')
runtime_int = [int(x1) for x1 in runtime]

print(runtime_int[0]*60 + runtime_int[1])

112

# Inflation of Domestic Grosses

In [138]:
import cpi
cpi.update()

In [140]:
cpi.get(19137)

24.1